kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: admin-creds
  annotations:
    avp.kubernetes.io/remove-missing: "true"
  labels:
    app: nexus3
stringData:
  username: admin
  password: docker.io
