apiVersion: v1
kind: Secret
metadata:
  name: ansible-secret
type: Opaque
stringData:
  VAULT_INFRA_TOKEN: docker.io
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: keycloak
data:
  admin-password: ZG9ja2VyLmlv
