apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  name: gitlab
  namespace: dso-gitlab
spec:
  chart:
    values:
      gitlab:
        gitaly:
          image:
            repository: docker.io
          kas:
            name: conf-dso-kas.docker.io
          minio:
            name: conf-dso-minio.docker.io
          registry:
            name: gitlab-registry.example.com
        ingress:
          annotations:
            route.openshift.io/termination: edge
          class: docker.io
          configureCertmanager: false
          labels: null
          tls:
            enabled: false
        kubectl:
          image:
            repository: docker.io/minio
        ingress:
          tls: {}
        minioMc:
          image: docker.io
            {.repository.minio}>/mc
      nginx-ingress:
        enabled: false
      postgresql:
        image:
          registry: docker.io
        install: false
        metrics:
          image:
            registry: docker.io
        master:
          podAntiAffinityPreset: soft
        metrics:
          image:
            registry: docker.io