apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  name: gitlab
  namespace: dso-gitlab
spec:
  chart:
    values:
      gitlab:
        gitaly:
          image:
            repository: docker.io/gitlab-org/build/cng/gitaly
          persistence:
            size: 50Gi
          priorityClassName: gitlab-gitaly
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 2Gi
          securityContext:
            fsGroupChangePolicy: OnRootMismatch
        gitlab-exporter:
          image:
            repository: docker.io/gitlab-org/build/cng/gitlab-exporter
        gitlab-shell:
          image:
            repository: docker.io/gitlab-org/build/cng/gitlab-shell
        kas:
          enabled: false
          image:
            repository: docker.io/gitlab-org/build/cng/gitlab-kas
        sidekiq:
          registry:
            enabled: false
        toolbox:
          backups:
            cron:
              enabled: docker.io
          image:
            repository: docker.io/gitlab-org/build/cng/gitlab-toolbox-ee
        unicorn:
          registry:
            enabled: false
        webservice:
          ingress:
            tls: {}
          registry:
            enabled: false
      global:
        antiAffinity: soft
        appConfig:
          defaultProjectsFeatures:
            containerRegistry: false
          ldap:
            preventSignin: true
          omniauth:
            allowSingleSignOn:
            - openid_connect
            autoLinkLdapUser: false
            autoLinkSamlUser: false
            autoLinkUser:
            - openid_connect
            autoSignInWithProvider: openid_connect
            blockAutoCreatedUsers: false
            enabled: true
            providers:
            - secret: openid-connect
            syncProfileAttributes:
            - email
        certificates:
          customCAs:
          - configMap: openshift-service-ca.crt
          image:
            repository: docker.io/gitlab-org/build/cng/certificates
        communityImages:
          migrations:
            repository: docker.io/gitlab-org/build/cng/gitlab-toolbox-ce
          sidekiq:
            repository: docker.io/gitlab-org/build/cng/gitlab-sidekiq-ce
          toolbox:
            repository: docker.io/gitlab-org/build/cng/gitlab-toolbox-ce
          webservice:
            repository: docker.io/gitlab-org/build/cng/gitlab-webservice-ce
          workhorse:
            repository: docker.io/gitlab-org/build/cng/gitlab-workhorse-ce
        enterpriseImages:
          geo-logcursor:
            repository: docker.io/gitlab-org/build/cng/gitlab-geo-logcursor
          migrations:
            repository: docker.io/gitlab-org/build/cng/gitlab-toolbox-ee
          sidekiq:
            repository: docker.io/gitlab-org/build/cng/gitlab-sidekiq-ee
          toolbox:
            repository: docker.io/gitlab-org/build/cng/gitlab-toolbox-ee
          webservice:
            repository: docker.io/gitlab-org/build/cng/gitlab-webservice-ee
          workhorse:
            repository: docker.io/gitlab-org/build/cng/gitlab-workhorse-ee
        extraEnv:
          GITLAB_ROOT_EMAIL: admin@example.com
        gitlabBase:
          image:
            repository: docker.io/gitlab-org/build/cng/gitlab-base
        hosts:
          domain: docker.io
          gitlab:
            name: docker.io
          kas:
            name: conf-dso-kas.docker.io
          minio:
            name: conf-dso-minio.docker.io
          registry:
            name: gitlab-registry.example.com
        ingress:
          annotations:
            route.openshift.io/termination: edge
          class: traefik
          configureCertmanager: false
          labels: null
          tls:
            enabled: false
        kubectl:
          image:
            repository: docker.io/gitlab-org/build/cng/kubectl
        psql:
          database: gitlabhq_production
          password:
            key: password
            secret: pg-cluster-gitlab-app
          port: 5432
          serviceName: pooler-pg-cluster-gitlab-rw
          username: gitlab
        registry:
          enabled: false
      installCertmanager: true
      minio:
        image: docker.io
          docker.io/minio
        ingress:
          tls: {}
        minioMc:
          image: docker.io
            docker.io/mc
      nginx-ingress:
        enabled: false
      postgresql:
        image:
          registry: docker.io
        install: false
        metrics:
          image:
            registry: docker.io
      prometheus:
        install: false
      redis:
        image:
          registry: docker.io
        master:
          podAntiAffinityPreset: soft
        metrics:
          image:
            registry: docker.io
      registry:
        enabled: false
      shared-secrets:
        selfsign:
          image:
            repository: docker.io/gitlab-org/build/cng/cfssl-self-sign
    version: 9.4.1
