apiVersion: v1
data:
  provider: <path:dso-sandbox/data/env/conf-dso/apps/gitlab/values#oidcProvider>
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/remove-missing: "true"
  name: openid-connect
type: Opaque
